<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaerahIndonesia extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinsi = [
            ['kode' => '11', 'name' => 'ACEH'],
            ['kode' => '12', 'name' => 'SUMATERA UTARA'],
            ['kode' => '13', 'name' => 'SUMATERA BARAT'],
            ['kode' => '14', 'name' => 'RIAU'],
            ['kode' => '15', 'name' => 'JAMBI'],
            ['kode' => '16', 'name' => 'SUMATERA SELATAN'],
            ['kode' => '17', 'name' => 'BENGKULU'],
            ['kode' => '18', 'name' => 'LAMPUNG'],
            ['kode' => '19', 'name' => 'KEPULAUAN BANGKA BELITUNG'],
            ['kode' => '21', 'name' => 'KEPULAUAN RIAU'],
            ['kode' => '31', 'name' => 'DKI JAKARTA'],
            ['kode' => '32', 'name' => 'JAWA BARAT'],
            ['kode' => '33', 'name' => 'JAWA TENGAH'],
            ['kode' => '34', 'name' => 'DI YOGYAKARTA'],
            ['kode' => '35', 'name' => 'JAWA TIMUR'],
            ['kode' => '36', 'name' => 'BANTEN'],
            ['kode' => '51', 'name' => 'BALI'],
            ['kode' => '52', 'name' => 'NUSA TENGGARA BARAT'],
            ['kode' => '53', 'name' => 'NUSA TENGGARA TIMUR'],
            ['kode' => '61', 'name' => 'KALIMANTAN BARAT'],
            ['kode' => '62', 'name' => 'KALIMANTAN TENGAH'],
            ['kode' => '63', 'name' => 'KALIMANTAN SELATAN'],
            ['kode' => '64', 'name' => 'KALIMANTAN TIMUR'],
            ['kode' => '65', 'name' => 'KALIMANTAN UTARA'],
            ['kode' => '71', 'name' => 'SULAWESI UTARA'],
            ['kode' => '72', 'name' => 'SULAWESI TENGAH'],
            ['kode' => '73', 'name' => 'SULAWESI SELATAN'],
            ['kode' => '74', 'name' => 'SULAWESI TENGGARA'],
            ['kode' => '75', 'name' => 'GORONTALO'],
            ['kode' => '76', 'name' => 'SULAWESI BARAT'],
            ['kode' => '81', 'name' => 'MALUKU'],
            ['kode' => '82', 'name' => 'MALUKU UTARA'],
            ['kode' => '91', 'name' => 'PAPUA BARAT'],
            ['kode' => '94', 'name' => 'PAPUA']
        ];

        $kabupaten = [
            ['kode' => '1101','kode_provinsi' => '11','name' => 'KABUPATEN SIMEULUE'],
            ['kode' => '1102','kode_provinsi' => '11','name' => 'KABUPATEN ACEH SINGKIL'],
            ['kode' => '1103','kode_provinsi' => '11','name' => 'KABUPATEN ACEH SELATAN'],
            ['kode' => '1104','kode_provinsi' => '11','name' => 'KABUPATEN ACEH TENGGARA'],
            ['kode' => '1105','kode_provinsi' => '11','name' => 'KABUPATEN ACEH TIMUR'],
            ['kode' => '1106','kode_provinsi' => '11','name' => 'KABUPATEN ACEH TENGAH'],
            ['kode' => '1107','kode_provinsi' => '11','name' => 'KABUPATEN ACEH BARAT'],
            ['kode' => '1108','kode_provinsi' => '11','name' => 'KABUPATEN ACEH BESAR'],
            ['kode' => '1109','kode_provinsi' => '11','name' => 'KABUPATEN PIDIE'],
            ['kode' => '1110','kode_provinsi' => '11','name' => 'KABUPATEN BIREUEN'],
            ['kode' => '1111','kode_provinsi' => '11','name' => 'KABUPATEN ACEH UTARA'],
            ['kode' => '1112','kode_provinsi' => '11','name' => 'KABUPATEN ACEH BARAT DAYA'],
            ['kode' => '1113','kode_provinsi' => '11','name' => 'KABUPATEN GAYO LUES'],
            ['kode' => '1114','kode_provinsi' => '11','name' => 'KABUPATEN ACEH TAMIANG'],
            ['kode' => '1115','kode_provinsi' => '11','name' => 'KABUPATEN NAGAN RAYA'],
            ['kode' => '1116','kode_provinsi' => '11','name' => 'KABUPATEN ACEH JAYA'],
            ['kode' => '1117','kode_provinsi' => '11','name' => 'KABUPATEN BENER MERIAH'],
            ['kode' => '1118','kode_provinsi' => '11','name' => 'KABUPATEN PIDIE JAYA'],
            ['kode' => '1171','kode_provinsi' => '11','name' => 'KOTA BANDA ACEH'],
            ['kode' => '1172','kode_provinsi' => '11','name' => 'KOTA SABANG'],
            ['kode' => '1173','kode_provinsi' => '11','name' => 'KOTA LANGSA'],
            ['kode' => '1174','kode_provinsi' => '11','name' => 'KOTA LHOKSEUMAWE'],
            ['kode' => '1175','kode_provinsi' => '11','name' => 'KOTA SUBULUSSALAM'],
            ['kode' => '1201','kode_provinsi' => '12','name' => 'KABUPATEN NIAS'],
            ['kode' => '1202','kode_provinsi' => '12','name' => 'KABUPATEN MANDAILING NATAL'],
            ['kode' => '1203','kode_provinsi' => '12','name' => 'KABUPATEN TAPANULI SELATAN'],
            ['kode' => '1204','kode_provinsi' => '12','name' => 'KABUPATEN TAPANULI TENGAH'],
            ['kode' => '1205','kode_provinsi' => '12','name' => 'KABUPATEN TAPANULI UTARA'],
            ['kode' => '1206','kode_provinsi' => '12','name' => 'KABUPATEN TOBA SAMOSIR'],
            ['kode' => '1207','kode_provinsi' => '12','name' => 'KABUPATEN LABUHAN BATU'],
            ['kode' => '1208','kode_provinsi' => '12','name' => 'KABUPATEN ASAHAN'],
            ['kode' => '1209','kode_provinsi' => '12','name' => 'KABUPATEN SIMALUNGUN'],
            ['kode' => '1210','kode_provinsi' => '12','name' => 'KABUPATEN DAIRI'],
            ['kode' => '1211','kode_provinsi' => '12','name' => 'KABUPATEN KARO'],
            ['kode' => '1212','kode_provinsi' => '12','name' => 'KABUPATEN DELI SERDANG'],
            ['kode' => '1213','kode_provinsi' => '12','name' => 'KABUPATEN LANGKAT'],
            ['kode' => '1214','kode_provinsi' => '12','name' => 'KABUPATEN NIAS SELATAN'],
            ['kode' => '1215','kode_provinsi' => '12','name' => 'KABUPATEN HUMBANG HASUNDUTAN'],
            ['kode' => '1216','kode_provinsi' => '12','name' => 'KABUPATEN PAKPAK BHARAT'],
            ['kode' => '1217','kode_provinsi' => '12','name' => 'KABUPATEN SAMOSIR'],
            ['kode' => '1218','kode_provinsi' => '12','name' => 'KABUPATEN SERDANG BEDAGAI'],
            ['kode' => '1219','kode_provinsi' => '12','name' => 'KABUPATEN BATU BARA'],
            ['kode' => '1220','kode_provinsi' => '12','name' => 'KABUPATEN PADANG LAWAS UTARA'],
            ['kode' => '1221','kode_provinsi' => '12','name' => 'KABUPATEN PADANG LAWAS'],
            ['kode' => '1222','kode_provinsi' => '12','name' => 'KABUPATEN LABUHAN BATU SELATAN'],
            ['kode' => '1223','kode_provinsi' => '12','name' => 'KABUPATEN LABUHAN BATU UTARA'],
            ['kode' => '1224','kode_provinsi' => '12','name' => 'KABUPATEN NIAS UTARA'],
            ['kode' => '1225','kode_provinsi' => '12','name' => 'KABUPATEN NIAS BARAT'],
            ['kode' => '1271','kode_provinsi' => '12','name' => 'KOTA SIBOLGA'],
            ['kode' => '1272','kode_provinsi' => '12','name' => 'KOTA TANJUNG BALAI'],
            ['kode' => '1273','kode_provinsi' => '12','name' => 'KOTA PEMATANG SIANTAR'],
            ['kode' => '1274','kode_provinsi' => '12','name' => 'KOTA TEBING TINGGI'],
            ['kode' => '1275','kode_provinsi' => '12','name' => 'KOTA MEDAN'],
            ['kode' => '1276','kode_provinsi' => '12','name' => 'KOTA BINJAI'],
            ['kode' => '1277','kode_provinsi' => '12','name' => 'KOTA PADANGSIDIMPUAN'],
            ['kode' => '1278','kode_provinsi' => '12','name' => 'KOTA GUNUNGSITOLI'],
            ['kode' => '1301','kode_provinsi' => '13','name' => 'KABUPATEN KEPULAUAN MENTAWAI'],
            ['kode' => '1302','kode_provinsi' => '13','name' => 'KABUPATEN PESISIR SELATAN'],
            ['kode' => '1303','kode_provinsi' => '13','name' => 'KABUPATEN SOLOK'],
            ['kode' => '1304','kode_provinsi' => '13','name' => 'KABUPATEN SIJUNJUNG'],
            ['kode' => '1305','kode_provinsi' => '13','name' => 'KABUPATEN TANAH DATAR'],
            ['kode' => '1306','kode_provinsi' => '13','name' => 'KABUPATEN PADANG PARIAMAN'],
            ['kode' => '1307','kode_provinsi' => '13','name' => 'KABUPATEN AGAM'],
            ['kode' => '1308','kode_provinsi' => '13','name' => 'KABUPATEN LIMA PULUH KOTA'],
            ['kode' => '1309','kode_provinsi' => '13','name' => 'KABUPATEN PASAMAN'],
            ['kode' => '1310','kode_provinsi' => '13','name' => 'KABUPATEN SOLOK SELATAN'],
            ['kode' => '1311','kode_provinsi' => '13','name' => 'KABUPATEN DHARMASRAYA'],
            ['kode' => '1312','kode_provinsi' => '13','name' => 'KABUPATEN PASAMAN BARAT'],
            ['kode' => '1371','kode_provinsi' => '13','name' => 'KOTA PADANG'],
            ['kode' => '1372','kode_provinsi' => '13','name' => 'KOTA SOLOK'],
            ['kode' => '1373','kode_provinsi' => '13','name' => 'KOTA SAWAH LUNTO'],
            ['kode' => '1374','kode_provinsi' => '13','name' => 'KOTA PADANG PANJANG'],
            ['kode' => '1375','kode_provinsi' => '13','name' => 'KOTA BUKITTINGGI'],
            ['kode' => '1376','kode_provinsi' => '13','name' => 'KOTA PAYAKUMBUH'],
            ['kode' => '1377','kode_provinsi' => '13','name' => 'KOTA PARIAMAN'],
            ['kode' => '1401','kode_provinsi' => '14','name' => 'KABUPATEN KUANTAN SINGINGI'],
            ['kode' => '1402','kode_provinsi' => '14','name' => 'KABUPATEN INDRAGIRI HULU'],
            ['kode' => '1403','kode_provinsi' => '14','name' => 'KABUPATEN INDRAGIRI HILIR'],
            ['kode' => '1404','kode_provinsi' => '14','name' => 'KABUPATEN PELALAWAN'],
            ['kode' => '1405','kode_provinsi' => '14','name' => 'KABUPATEN S I A K'],
            ['kode' => '1406','kode_provinsi' => '14','name' => 'KABUPATEN KAMPAR'],
            ['kode' => '1407','kode_provinsi' => '14','name' => 'KABUPATEN ROKAN HULU'],
            ['kode' => '1408','kode_provinsi' => '14','name' => 'KABUPATEN BENGKALIS'],
            ['kode' => '1409','kode_provinsi' => '14','name' => 'KABUPATEN ROKAN HILIR'],
            ['kode' => '1410','kode_provinsi' => '14','name' => 'KABUPATEN KEPULAUAN MERANTI'],
            ['kode' => '1471','kode_provinsi' => '14','name' => 'KOTA PEKANBARU'],
            ['kode' => '1473','kode_provinsi' => '14','name' => 'KOTA D U M A I'],
            ['kode' => '1501','kode_provinsi' => '15','name' => 'KABUPATEN KERINCI'],
            ['kode' => '1502','kode_provinsi' => '15','name' => 'KABUPATEN MERANGIN'],
            ['kode' => '1503','kode_provinsi' => '15','name' => 'KABUPATEN SAROLANGUN'],
            ['kode' => '1504','kode_provinsi' => '15','name' => 'KABUPATEN BATANG HARI'],
            ['kode' => '1505','kode_provinsi' => '15','name' => 'KABUPATEN MUARO JAMBI'],
            ['kode' => '1506','kode_provinsi' => '15','name' => 'KABUPATEN TANJUNG JABUNG TIMUR'],
            ['kode' => '1507','kode_provinsi' => '15','name' => 'KABUPATEN TANJUNG JABUNG BARAT'],
            ['kode' => '1508','kode_provinsi' => '15','name' => 'KABUPATEN TEBO'],
            ['kode' => '1509','kode_provinsi' => '15','name' => 'KABUPATEN BUNGO'],
            ['kode' => '1571','kode_provinsi' => '15','name' => 'KOTA JAMBI'],
            ['kode' => '1572','kode_provinsi' => '15','name' => 'KOTA SUNGAI PENUH'],
            ['kode' => '1601','kode_provinsi' => '16','name' => 'KABUPATEN OGAN KOMERING ULU'],
            ['kode' => '1602','kode_provinsi' => '16','name' => 'KABUPATEN OGAN KOMERING ILIR'],
            ['kode' => '1603','kode_provinsi' => '16','name' => 'KABUPATEN MUARA ENIM'],
            ['kode' => '1604','kode_provinsi' => '16','name' => 'KABUPATEN LAHAT'],
            ['kode' => '1605','kode_provinsi' => '16','name' => 'KABUPATEN MUSI RAWAS'],
            ['kode' => '1606','kode_provinsi' => '16','name' => 'KABUPATEN MUSI BANYUASIN'],
            ['kode' => '1607','kode_provinsi' => '16','name' => 'KABUPATEN BANYU ASIN'],
            ['kode' => '1608','kode_provinsi' => '16','name' => 'KABUPATEN OGAN KOMERING ULU SELATAN'],
            ['kode' => '1609','kode_provinsi' => '16','name' => 'KABUPATEN OGAN KOMERING ULU TIMUR'],
            ['kode' => '1610','kode_provinsi' => '16','name' => 'KABUPATEN OGAN ILIR'],
            ['kode' => '1611','kode_provinsi' => '16','name' => 'KABUPATEN EMPAT LAWANG'],
            ['kode' => '1612','kode_provinsi' => '16','name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
            ['kode' => '1613','kode_provinsi' => '16','name' => 'KABUPATEN MUSI RAWAS UTARA'],
            ['kode' => '1671','kode_provinsi' => '16','name' => 'KOTA PALEMBANG'],
            ['kode' => '1672','kode_provinsi' => '16','name' => 'KOTA PRABUMULIH'],
            ['kode' => '1673','kode_provinsi' => '16','name' => 'KOTA PAGAR ALAM'],
            ['kode' => '1674','kode_provinsi' => '16','name' => 'KOTA LUBUKLINGGAU'],
            ['kode' => '1701','kode_provinsi' => '17','name' => 'KABUPATEN BENGKULU SELATAN'],
            ['kode' => '1702','kode_provinsi' => '17','name' => 'KABUPATEN REJANG LEBONG'],
            ['kode' => '1703','kode_provinsi' => '17','name' => 'KABUPATEN BENGKULU UTARA'],
            ['kode' => '1704','kode_provinsi' => '17','name' => 'KABUPATEN KAUR'],
            ['kode' => '1705','kode_provinsi' => '17','name' => 'KABUPATEN SELUMA'],
            ['kode' => '1706','kode_provinsi' => '17','name' => 'KABUPATEN MUKOMUKO'],
            ['kode' => '1707','kode_provinsi' => '17','name' => 'KABUPATEN LEBONG'],
            ['kode' => '1708','kode_provinsi' => '17','name' => 'KABUPATEN KEPAHIANG'],
            ['kode' => '1709','kode_provinsi' => '17','name' => 'KABUPATEN BENGKULU TENGAH'],
            ['kode' => '1771','kode_provinsi' => '17','name' => 'KOTA BENGKULU'],
            ['kode' => '1801','kode_provinsi' => '18','name' => 'KABUPATEN LAMPUNG BARAT'],
            ['kode' => '1802','kode_provinsi' => '18','name' => 'KABUPATEN TANGGAMUS'],
            ['kode' => '1803','kode_provinsi' => '18','name' => 'KABUPATEN LAMPUNG SELATAN'],
            ['kode' => '1804','kode_provinsi' => '18','name' => 'KABUPATEN LAMPUNG TIMUR'],
            ['kode' => '1805','kode_provinsi' => '18','name' => 'KABUPATEN LAMPUNG TENGAH'],
            ['kode' => '1806','kode_provinsi' => '18','name' => 'KABUPATEN LAMPUNG UTARA'],
            ['kode' => '1807','kode_provinsi' => '18','name' => 'KABUPATEN WAY KANAN'],
            ['kode' => '1808','kode_provinsi' => '18','name' => 'KABUPATEN TULANGBAWANG'],
            ['kode' => '1809','kode_provinsi' => '18','name' => 'KABUPATEN PESAWARAN'],
            ['kode' => '1810','kode_provinsi' => '18','name' => 'KABUPATEN PRINGSEWU'],
            ['kode' => '1811','kode_provinsi' => '18','name' => 'KABUPATEN MESUJI'],
            ['kode' => '1812','kode_provinsi' => '18','name' => 'KABUPATEN TULANG BAWANG BARAT'],
            ['kode' => '1813','kode_provinsi' => '18','name' => 'KABUPATEN PESISIR BARAT'],
            ['kode' => '1871','kode_provinsi' => '18','name' => 'KOTA BANDAR LAMPUNG'],
            ['kode' => '1872','kode_provinsi' => '18','name' => 'KOTA METRO'],
            ['kode' => '1901','kode_provinsi' => '19','name' => 'KABUPATEN BANGKA'],
            ['kode' => '1902','kode_provinsi' => '19','name' => 'KABUPATEN BELITUNG'],
            ['kode' => '1903','kode_provinsi' => '19','name' => 'KABUPATEN BANGKA BARAT'],
            ['kode' => '1904','kode_provinsi' => '19','name' => 'KABUPATEN BANGKA TENGAH'],
            ['kode' => '1905','kode_provinsi' => '19','name' => 'KABUPATEN BANGKA SELATAN'],
            ['kode' => '1906','kode_provinsi' => '19','name' => 'KABUPATEN BELITUNG TIMUR'],
            ['kode' => '1971','kode_provinsi' => '19','name' => 'KOTA PANGKAL PINANG'],
            ['kode' => '2101','kode_provinsi' => '21','name' => 'KABUPATEN KARIMUN'],
            ['kode' => '2102','kode_provinsi' => '21','name' => 'KABUPATEN BINTAN'],
            ['kode' => '2103','kode_provinsi' => '21','name' => 'KABUPATEN NATUNA'],
            ['kode' => '2104','kode_provinsi' => '21','name' => 'KABUPATEN LINGGA'],
            ['kode' => '2105','kode_provinsi' => '21','name' => 'KABUPATEN KEPULAUAN ANAMBAS'],
            ['kode' => '2171','kode_provinsi' => '21','name' => 'KOTA B A T A M'],
            ['kode' => '2172','kode_provinsi' => '21','name' => 'KOTA TANJUNG PINANG'],
            ['kode' => '3101','kode_provinsi' => '31','name' => 'KABUPATEN KEPULAUAN SERIBU'],
            ['kode' => '3171','kode_provinsi' => '31','name' => 'KOTA JAKARTA SELATAN'],
            ['kode' => '3172','kode_provinsi' => '31','name' => 'KOTA JAKARTA TIMUR'],
            ['kode' => '3173','kode_provinsi' => '31','name' => 'KOTA JAKARTA PUSAT'],
            ['kode' => '3174','kode_provinsi' => '31','name' => 'KOTA JAKARTA BARAT'],
            ['kode' => '3175','kode_provinsi' => '31','name' => 'KOTA JAKARTA UTARA'],
            ['kode' => '3201','kode_provinsi' => '32','name' => 'KABUPATEN BOGOR'],
            ['kode' => '3202','kode_provinsi' => '32','name' => 'KABUPATEN SUKABUMI'],
            ['kode' => '3203','kode_provinsi' => '32','name' => 'KABUPATEN CIANJUR'],
            ['kode' => '3204','kode_provinsi' => '32','name' => 'KABUPATEN BANDUNG'],
            ['kode' => '3205','kode_provinsi' => '32','name' => 'KABUPATEN GARUT'],
            ['kode' => '3206','kode_provinsi' => '32','name' => 'KABUPATEN TASIKMALAYA'],
            ['kode' => '3207','kode_provinsi' => '32','name' => 'KABUPATEN CIAMIS'],
            ['kode' => '3208','kode_provinsi' => '32','name' => 'KABUPATEN KUNINGAN'],
            ['kode' => '3209','kode_provinsi' => '32','name' => 'KABUPATEN CIREBON'],
            ['kode' => '3210','kode_provinsi' => '32','name' => 'KABUPATEN MAJALENGKA'],
            ['kode' => '3211','kode_provinsi' => '32','name' => 'KABUPATEN SUMEDANG'],
            ['kode' => '3212','kode_provinsi' => '32','name' => 'KABUPATEN INDRAMAYU'],
            ['kode' => '3213','kode_provinsi' => '32','name' => 'KABUPATEN SUBANG'],
            ['kode' => '3214','kode_provinsi' => '32','name' => 'KABUPATEN PURWAKARTA'],
            ['kode' => '3215','kode_provinsi' => '32','name' => 'KABUPATEN KARAWANG'],
            ['kode' => '3216','kode_provinsi' => '32','name' => 'KABUPATEN BEKASI'],
            ['kode' => '3217','kode_provinsi' => '32','name' => 'KABUPATEN BANDUNG BARAT'],
            ['kode' => '3218','kode_provinsi' => '32','name' => 'KABUPATEN PANGANDARAN'],
            ['kode' => '3271','kode_provinsi' => '32','name' => 'KOTA BOGOR'],
            ['kode' => '3272','kode_provinsi' => '32','name' => 'KOTA SUKABUMI'],
            ['kode' => '3273','kode_provinsi' => '32','name' => 'KOTA BANDUNG'],
            ['kode' => '3274','kode_provinsi' => '32','name' => 'KOTA CIREBON'],
            ['kode' => '3275','kode_provinsi' => '32','name' => 'KOTA BEKASI'],
            ['kode' => '3276','kode_provinsi' => '32','name' => 'KOTA DEPOK'],
            ['kode' => '3277','kode_provinsi' => '32','name' => 'KOTA CIMAHI'],
            ['kode' => '3278','kode_provinsi' => '32','name' => 'KOTA TASIKMALAYA'],
            ['kode' => '3279','kode_provinsi' => '32','name' => 'KOTA BANJAR'],
            ['kode' => '3301','kode_provinsi' => '33','name' => 'KABUPATEN CILACAP'],
            ['kode' => '3302','kode_provinsi' => '33','name' => 'KABUPATEN BANYUMAS'],
            ['kode' => '3303','kode_provinsi' => '33','name' => 'KABUPATEN PURBALINGGA'],
            ['kode' => '3304','kode_provinsi' => '33','name' => 'KABUPATEN BANJARNEGARA'],
            ['kode' => '3305','kode_provinsi' => '33','name' => 'KABUPATEN KEBUMEN'],
            ['kode' => '3306','kode_provinsi' => '33','name' => 'KABUPATEN PURWOREJO'],
            ['kode' => '3307','kode_provinsi' => '33','name' => 'KABUPATEN WONOSOBO'],
            ['kode' => '3308','kode_provinsi' => '33','name' => 'KABUPATEN MAGELANG'],
            ['kode' => '3309','kode_provinsi' => '33','name' => 'KABUPATEN BOYOLALI'],
            ['kode' => '3310','kode_provinsi' => '33','name' => 'KABUPATEN KLATEN'],
            ['kode' => '3311','kode_provinsi' => '33','name' => 'KABUPATEN SUKOHARJO'],
            ['kode' => '3312','kode_provinsi' => '33','name' => 'KABUPATEN WONOGIRI'],
            ['kode' => '3313','kode_provinsi' => '33','name' => 'KABUPATEN KARANGANYAR'],
            ['kode' => '3314','kode_provinsi' => '33','name' => 'KABUPATEN SRAGEN'],
            ['kode' => '3315','kode_provinsi' => '33','name' => 'KABUPATEN GROBOGAN'],
            ['kode' => '3316','kode_provinsi' => '33','name' => 'KABUPATEN BLORA'],
            ['kode' => '3317','kode_provinsi' => '33','name' => 'KABUPATEN REMBANG'],
            ['kode' => '3318','kode_provinsi' => '33','name' => 'KABUPATEN PATI'],
            ['kode' => '3319','kode_provinsi' => '33','name' => 'KABUPATEN KUDUS'],
            ['kode' => '3320','kode_provinsi' => '33','name' => 'KABUPATEN JEPARA'],
            ['kode' => '3321','kode_provinsi' => '33','name' => 'KABUPATEN DEMAK'],
            ['kode' => '3322','kode_provinsi' => '33','name' => 'KABUPATEN SEMARANG'],
            ['kode' => '3323','kode_provinsi' => '33','name' => 'KABUPATEN TEMANGGUNG'],
            ['kode' => '3324','kode_provinsi' => '33','name' => 'KABUPATEN KENDAL'],
            ['kode' => '3325','kode_provinsi' => '33','name' => 'KABUPATEN BATANG'],
            ['kode' => '3326','kode_provinsi' => '33','name' => 'KABUPATEN PEKALONGAN'],
            ['kode' => '3327','kode_provinsi' => '33','name' => 'KABUPATEN PEMALANG'],
            ['kode' => '3328','kode_provinsi' => '33','name' => 'KABUPATEN TEGAL'],
            ['kode' => '3329','kode_provinsi' => '33','name' => 'KABUPATEN BREBES'],
            ['kode' => '3371','kode_provinsi' => '33','name' => 'KOTA MAGELANG'],
            ['kode' => '3372','kode_provinsi' => '33','name' => 'KOTA SURAKARTA'],
            ['kode' => '3373','kode_provinsi' => '33','name' => 'KOTA SALATIGA'],
            ['kode' => '3374','kode_provinsi' => '33','name' => 'KOTA SEMARANG'],
            ['kode' => '3375','kode_provinsi' => '33','name' => 'KOTA PEKALONGAN'],
            ['kode' => '3376','kode_provinsi' => '33','name' => 'KOTA TEGAL'],
            ['kode' => '3401','kode_provinsi' => '34','name' => 'KABUPATEN KULON PROGO'],
            ['kode' => '3402','kode_provinsi' => '34','name' => 'KABUPATEN BANTUL'],
            ['kode' => '3403','kode_provinsi' => '34','name' => 'KABUPATEN GUNUNG KIDUL'],
            ['kode' => '3404','kode_provinsi' => '34','name' => 'KABUPATEN SLEMAN'],
            ['kode' => '3471','kode_provinsi' => '34','name' => 'KOTA YOGYAKARTA'],
            ['kode' => '3501','kode_provinsi' => '35','name' => 'KABUPATEN PACITAN'],
            ['kode' => '3502','kode_provinsi' => '35','name' => 'KABUPATEN PONOROGO'],
            ['kode' => '3503','kode_provinsi' => '35','name' => 'KABUPATEN TRENGGALEK'],
            ['kode' => '3504','kode_provinsi' => '35','name' => 'KABUPATEN TULUNGAGUNG'],
            ['kode' => '3505','kode_provinsi' => '35','name' => 'KABUPATEN BLITAR'],
            ['kode' => '3506','kode_provinsi' => '35','name' => 'KABUPATEN KEDIRI'],
            ['kode' => '3507','kode_provinsi' => '35','name' => 'KABUPATEN MALANG'],
            ['kode' => '3508','kode_provinsi' => '35','name' => 'KABUPATEN LUMAJANG'],
            ['kode' => '3509','kode_provinsi' => '35','name' => 'KABUPATEN JEMBER'],
            ['kode' => '3510','kode_provinsi' => '35','name' => 'KABUPATEN BANYUWANGI'],
            ['kode' => '3511','kode_provinsi' => '35','name' => 'KABUPATEN BONDOWOSO'],
            ['kode' => '3512','kode_provinsi' => '35','name' => 'KABUPATEN SITUBONDO'],
            ['kode' => '3513','kode_provinsi' => '35','name' => 'KABUPATEN PROBOLINGGO'],
            ['kode' => '3514','kode_provinsi' => '35','name' => 'KABUPATEN PASURUAN'],
            ['kode' => '3515','kode_provinsi' => '35','name' => 'KABUPATEN SIDOARJO'],
            ['kode' => '3516','kode_provinsi' => '35','name' => 'KABUPATEN MOJOKERTO'],
            ['kode' => '3517','kode_provinsi' => '35','name' => 'KABUPATEN JOMBANG'],
            ['kode' => '3518','kode_provinsi' => '35','name' => 'KABUPATEN NGANJUK'],
            ['kode' => '3519','kode_provinsi' => '35','name' => 'KABUPATEN MADIUN'],
            ['kode' => '3520','kode_provinsi' => '35','name' => 'KABUPATEN MAGETAN'],
            ['kode' => '3521','kode_provinsi' => '35','name' => 'KABUPATEN NGAWI'],
            ['kode' => '3522','kode_provinsi' => '35','name' => 'KABUPATEN BOJONEGORO'],
            ['kode' => '3523','kode_provinsi' => '35','name' => 'KABUPATEN TUBAN'],
            ['kode' => '3524','kode_provinsi' => '35','name' => 'KABUPATEN LAMONGAN'],
            ['kode' => '3525','kode_provinsi' => '35','name' => 'KABUPATEN GRESIK'],
            ['kode' => '3526','kode_provinsi' => '35','name' => 'KABUPATEN BANGKALAN'],
            ['kode' => '3527','kode_provinsi' => '35','name' => 'KABUPATEN SAMPANG'],
            ['kode' => '3528','kode_provinsi' => '35','name' => 'KABUPATEN PAMEKASAN'],
            ['kode' => '3529','kode_provinsi' => '35','name' => 'KABUPATEN SUMENEP'],
            ['kode' => '3571','kode_provinsi' => '35','name' => 'KOTA KEDIRI'],
            ['kode' => '3572','kode_provinsi' => '35','name' => 'KOTA BLITAR'],
            ['kode' => '3573','kode_provinsi' => '35','name' => 'KOTA MALANG'],
            ['kode' => '3574','kode_provinsi' => '35','name' => 'KOTA PROBOLINGGO'],
            ['kode' => '3575','kode_provinsi' => '35','name' => 'KOTA PASURUAN'],
            ['kode' => '3576','kode_provinsi' => '35','name' => 'KOTA MOJOKERTO'],
            ['kode' => '3577','kode_provinsi' => '35','name' => 'KOTA MADIUN'],
            ['kode' => '3578','kode_provinsi' => '35','name' => 'KOTA SURABAYA'],
            ['kode' => '3579','kode_provinsi' => '35','name' => 'KOTA BATU'],
            ['kode' => '3601','kode_provinsi' => '36','name' => 'KABUPATEN PANDEGLANG'],
            ['kode' => '3602','kode_provinsi' => '36','name' => 'KABUPATEN LEBAK'],
            ['kode' => '3603','kode_provinsi' => '36','name' => 'KABUPATEN TANGERANG'],
            ['kode' => '3604','kode_provinsi' => '36','name' => 'KABUPATEN SERANG'],
            ['kode' => '3671','kode_provinsi' => '36','name' => 'KOTA TANGERANG'],
            ['kode' => '3672','kode_provinsi' => '36','name' => 'KOTA CILEGON'],
            ['kode' => '3673','kode_provinsi' => '36','name' => 'KOTA SERANG'],
            ['kode' => '3674','kode_provinsi' => '36','name' => 'KOTA TANGERANG SELATAN'],
            ['kode' => '5101','kode_provinsi' => '51','name' => 'KABUPATEN JEMBRANA'],
            ['kode' => '5102','kode_provinsi' => '51','name' => 'KABUPATEN TABANAN'],
            ['kode' => '5103','kode_provinsi' => '51','name' => 'KABUPATEN BADUNG'],
            ['kode' => '5104','kode_provinsi' => '51','name' => 'KABUPATEN GIANYAR'],
            ['kode' => '5105','kode_provinsi' => '51','name' => 'KABUPATEN KLUNGKUNG'],
            ['kode' => '5106','kode_provinsi' => '51','name' => 'KABUPATEN BANGLI'],
            ['kode' => '5107','kode_provinsi' => '51','name' => 'KABUPATEN KARANG ASEM'],
            ['kode' => '5108','kode_provinsi' => '51','name' => 'KABUPATEN BULELENG'],
            ['kode' => '5171','kode_provinsi' => '51','name' => 'KOTA DENPASAR'],
            ['kode' => '5201','kode_provinsi' => '52','name' => 'KABUPATEN LOMBOK BARAT'],
            ['kode' => '5202','kode_provinsi' => '52','name' => 'KABUPATEN LOMBOK TENGAH'],
            ['kode' => '5203','kode_provinsi' => '52','name' => 'KABUPATEN LOMBOK TIMUR'],
            ['kode' => '5204','kode_provinsi' => '52','name' => 'KABUPATEN SUMBAWA'],
            ['kode' => '5205','kode_provinsi' => '52','name' => 'KABUPATEN DOMPU'],
            ['kode' => '5206','kode_provinsi' => '52','name' => 'KABUPATEN BIMA'],
            ['kode' => '5207','kode_provinsi' => '52','name' => 'KABUPATEN SUMBAWA BARAT'],
            ['kode' => '5208','kode_provinsi' => '52','name' => 'KABUPATEN LOMBOK UTARA'],
            ['kode' => '5271','kode_provinsi' => '52','name' => 'KOTA MATARAM'],
            ['kode' => '5272','kode_provinsi' => '52','name' => 'KOTA BIMA'],
            ['kode' => '5301','kode_provinsi' => '53','name' => 'KABUPATEN SUMBA BARAT'],
            ['kode' => '5302','kode_provinsi' => '53','name' => 'KABUPATEN SUMBA TIMUR'],
            ['kode' => '5303','kode_provinsi' => '53','name' => 'KABUPATEN KUPANG'],
            ['kode' => '5304','kode_provinsi' => '53','name' => 'KABUPATEN TIMOR TENGAH SELATAN'],
            ['kode' => '5305','kode_provinsi' => '53','name' => 'KABUPATEN TIMOR TENGAH UTARA'],
            ['kode' => '5306','kode_provinsi' => '53','name' => 'KABUPATEN BELU'],
            ['kode' => '5307','kode_provinsi' => '53','name' => 'KABUPATEN ALOR'],
            ['kode' => '5308','kode_provinsi' => '53','name' => 'KABUPATEN LEMBATA'],
            ['kode' => '5309','kode_provinsi' => '53','name' => 'KABUPATEN FLORES TIMUR'],
            ['kode' => '5310','kode_provinsi' => '53','name' => 'KABUPATEN SIKKA'],
            ['kode' => '5311','kode_provinsi' => '53','name' => 'KABUPATEN ENDE'],
            ['kode' => '5312','kode_provinsi' => '53','name' => 'KABUPATEN NGADA'],
            ['kode' => '5313','kode_provinsi' => '53','name' => 'KABUPATEN MANGGARAI'],
            ['kode' => '5314','kode_provinsi' => '53','name' => 'KABUPATEN ROTE NDAO'],
            ['kode' => '5315','kode_provinsi' => '53','name' => 'KABUPATEN MANGGARAI BARAT'],
            ['kode' => '5316','kode_provinsi' => '53','name' => 'KABUPATEN SUMBA TENGAH'],
            ['kode' => '5317','kode_provinsi' => '53','name' => 'KABUPATEN SUMBA BARAT DAYA'],
            ['kode' => '5318','kode_provinsi' => '53','name' => 'KABUPATEN NAGEKEO'],
            ['kode' => '5319','kode_provinsi' => '53','name' => 'KABUPATEN MANGGARAI TIMUR'],
            ['kode' => '5320','kode_provinsi' => '53','name' => 'KABUPATEN SABU RAIJUA'],
            ['kode' => '5321','kode_provinsi' => '53','name' => 'KABUPATEN MALAKA'],
            ['kode' => '5371','kode_provinsi' => '53','name' => 'KOTA KUPANG'],
            ['kode' => '6101','kode_provinsi' => '61','name' => 'KABUPATEN SAMBAS'],
            ['kode' => '6102','kode_provinsi' => '61','name' => 'KABUPATEN BENGKAYANG'],
            ['kode' => '6103','kode_provinsi' => '61','name' => 'KABUPATEN LANDAK'],
            ['kode' => '6104','kode_provinsi' => '61','name' => 'KABUPATEN MEMPAWAH'],
            ['kode' => '6105','kode_provinsi' => '61','name' => 'KABUPATEN SANGGAU'],
            ['kode' => '6106','kode_provinsi' => '61','name' => 'KABUPATEN KETAPANG'],
            ['kode' => '6107','kode_provinsi' => '61','name' => 'KABUPATEN SINTANG'],
            ['kode' => '6108','kode_provinsi' => '61','name' => 'KABUPATEN KAPUAS HULU'],
            ['kode' => '6109','kode_provinsi' => '61','name' => 'KABUPATEN SEKADAU'],
            ['kode' => '6110','kode_provinsi' => '61','name' => 'KABUPATEN MELAWI'],
            ['kode' => '6111','kode_provinsi' => '61','name' => 'KABUPATEN KAYONG UTARA'],
            ['kode' => '6112','kode_provinsi' => '61','name' => 'KABUPATEN KUBU RAYA'],
            ['kode' => '6171','kode_provinsi' => '61','name' => 'KOTA PONTIANAK'],
            ['kode' => '6172','kode_provinsi' => '61','name' => 'KOTA SINGKAWANG'],
            ['kode' => '6201','kode_provinsi' => '62','name' => 'KABUPATEN KOTAWARINGIN BARAT'],
            ['kode' => '6202','kode_provinsi' => '62','name' => 'KABUPATEN KOTAWARINGIN TIMUR'],
            ['kode' => '6203','kode_provinsi' => '62','name' => 'KABUPATEN KAPUAS'],
            ['kode' => '6204','kode_provinsi' => '62','name' => 'KABUPATEN BARITO SELATAN'],
            ['kode' => '6205','kode_provinsi' => '62','name' => 'KABUPATEN BARITO UTARA'],
            ['kode' => '6206','kode_provinsi' => '62','name' => 'KABUPATEN SUKAMARA'],
            ['kode' => '6207','kode_provinsi' => '62','name' => 'KABUPATEN LAMANDAU'],
            ['kode' => '6208','kode_provinsi' => '62','name' => 'KABUPATEN SERUYAN'],
            ['kode' => '6209','kode_provinsi' => '62','name' => 'KABUPATEN KATINGAN'],
            ['kode' => '6210','kode_provinsi' => '62','name' => 'KABUPATEN PULANG PISAU'],
            ['kode' => '6211','kode_provinsi' => '62','name' => 'KABUPATEN GUNUNG MAS'],
            ['kode' => '6212','kode_provinsi' => '62','name' => 'KABUPATEN BARITO TIMUR'],
            ['kode' => '6213','kode_provinsi' => '62','name' => 'KABUPATEN MURUNG RAYA'],
            ['kode' => '6271','kode_provinsi' => '62','name' => 'KOTA PALANGKA RAYA'],
            ['kode' => '6301','kode_provinsi' => '63','name' => 'KABUPATEN TANAH LAUT'],
            ['kode' => '6302','kode_provinsi' => '63','name' => 'KABUPATEN KOTA BARU'],
            ['kode' => '6303','kode_provinsi' => '63','name' => 'KABUPATEN BANJAR'],
            ['kode' => '6304','kode_provinsi' => '63','name' => 'KABUPATEN BARITO KUALA'],
            ['kode' => '6305','kode_provinsi' => '63','name' => 'KABUPATEN TAPIN'],
            ['kode' => '6306','kode_provinsi' => '63','name' => 'KABUPATEN HULU SUNGAI SELATAN'],
            ['kode' => '6307','kode_provinsi' => '63','name' => 'KABUPATEN HULU SUNGAI TENGAH'],
            ['kode' => '6308','kode_provinsi' => '63','name' => 'KABUPATEN HULU SUNGAI UTARA'],
            ['kode' => '6309','kode_provinsi' => '63','name' => 'KABUPATEN TABALONG'],
            ['kode' => '6310','kode_provinsi' => '63','name' => 'KABUPATEN TANAH BUMBU'],
            ['kode' => '6311','kode_provinsi' => '63','name' => 'KABUPATEN BALANGAN'],
            ['kode' => '6371','kode_provinsi' => '63','name' => 'KOTA BANJARMASIN'],
            ['kode' => '6372','kode_provinsi' => '63','name' => 'KOTA BANJAR BARU'],
            ['kode' => '6401','kode_provinsi' => '64','name' => 'KABUPATEN PASER'],
            ['kode' => '6402','kode_provinsi' => '64','name' => 'KABUPATEN KUTAI BARAT'],
            ['kode' => '6403','kode_provinsi' => '64','name' => 'KABUPATEN KUTAI KARTANEGARA'],
            ['kode' => '6404','kode_provinsi' => '64','name' => 'KABUPATEN KUTAI TIMUR'],
            ['kode' => '6405','kode_provinsi' => '64','name' => 'KABUPATEN BERAU'],
            ['kode' => '6409','kode_provinsi' => '64','name' => 'KABUPATEN PENAJAM PASER UTARA'],
            ['kode' => '6411','kode_provinsi' => '64','name' => 'KABUPATEN MAHAKAM HULU'],
            ['kode' => '6471','kode_provinsi' => '64','name' => 'KOTA BALIKPAPAN'],
            ['kode' => '6472','kode_provinsi' => '64','name' => 'KOTA SAMARINDA'],
            ['kode' => '6474','kode_provinsi' => '64','name' => 'KOTA BONTANG'],
            ['kode' => '6501','kode_provinsi' => '65','name' => 'KABUPATEN MALINAU'],
            ['kode' => '6502','kode_provinsi' => '65','name' => 'KABUPATEN BULUNGAN'],
            ['kode' => '6503','kode_provinsi' => '65','name' => 'KABUPATEN TANA TIDUNG'],
            ['kode' => '6504','kode_provinsi' => '65','name' => 'KABUPATEN NUNUKAN'],
            ['kode' => '6571','kode_provinsi' => '65','name' => 'KOTA TARAKAN'],
            ['kode' => '7101','kode_provinsi' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW'],
            ['kode' => '7102','kode_provinsi' => '71','name' => 'KABUPATEN MINAHASA'],
            ['kode' => '7103','kode_provinsi' => '71','name' => 'KABUPATEN KEPULAUAN SANGIHE'],
            ['kode' => '7104','kode_provinsi' => '71','name' => 'KABUPATEN KEPULAUAN TALAUD'],
            ['kode' => '7105','kode_provinsi' => '71','name' => 'KABUPATEN MINAHASA SELATAN'],
            ['kode' => '7106','kode_provinsi' => '71','name' => 'KABUPATEN MINAHASA UTARA'],
            ['kode' => '7107','kode_provinsi' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW UTARA'],
            ['kode' => '7108','kode_provinsi' => '71','name' => 'KABUPATEN SIAU TAGULANDANG BIARO'],
            ['kode' => '7109','kode_provinsi' => '71','name' => 'KABUPATEN MINAHASA TENGGARA'],
            ['kode' => '7110','kode_provinsi' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
            ['kode' => '7111','kode_provinsi' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
            ['kode' => '7171','kode_provinsi' => '71','name' => 'KOTA MANADO'],
            ['kode' => '7172','kode_provinsi' => '71','name' => 'KOTA BITUNG'],
            ['kode' => '7173','kode_provinsi' => '71','name' => 'KOTA TOMOHON'],
            ['kode' => '7174','kode_provinsi' => '71','name' => 'KOTA KOTAMOBAGU'],
            ['kode' => '7201','kode_provinsi' => '72','name' => 'KABUPATEN BANGGAI KEPULAUAN'],
            ['kode' => '7202','kode_provinsi' => '72','name' => 'KABUPATEN BANGGAI'],
            ['kode' => '7203','kode_provinsi' => '72','name' => 'KABUPATEN MOROWALI'],
            ['kode' => '7204','kode_provinsi' => '72','name' => 'KABUPATEN POSO'],
            ['kode' => '7205','kode_provinsi' => '72','name' => 'KABUPATEN DONGGALA'],
            ['kode' => '7206','kode_provinsi' => '72','name' => 'KABUPATEN TOLI-TOLI'],
            ['kode' => '7207','kode_provinsi' => '72','name' => 'KABUPATEN BUOL'],
            ['kode' => '7208','kode_provinsi' => '72','name' => 'KABUPATEN PARIGI MOUTONG'],
            ['kode' => '7209','kode_provinsi' => '72','name' => 'KABUPATEN TOJO UNA-UNA'],
            ['kode' => '7210','kode_provinsi' => '72','name' => 'KABUPATEN SIGI'],
            ['kode' => '7211','kode_provinsi' => '72','name' => 'KABUPATEN BANGGAI LAUT'],
            ['kode' => '7212','kode_provinsi' => '72','name' => 'KABUPATEN MOROWALI UTARA'],
            ['kode' => '7271','kode_provinsi' => '72','name' => 'KOTA PALU'],
            ['kode' => '7301','kode_provinsi' => '73','name' => 'KABUPATEN KEPULAUAN SELAYAR'],
            ['kode' => '7302','kode_provinsi' => '73','name' => 'KABUPATEN BULUKUMBA'],
            ['kode' => '7303','kode_provinsi' => '73','name' => 'KABUPATEN BANTAENG'],
            ['kode' => '7304','kode_provinsi' => '73','name' => 'KABUPATEN JENEPONTO'],
            ['kode' => '7305','kode_provinsi' => '73','name' => 'KABUPATEN TAKALAR'],
            ['kode' => '7306','kode_provinsi' => '73','name' => 'KABUPATEN GOWA'],
            ['kode' => '7307','kode_provinsi' => '73','name' => 'KABUPATEN SINJAI'],
            ['kode' => '7308','kode_provinsi' => '73','name' => 'KABUPATEN MAROS'],
            ['kode' => '7309','kode_provinsi' => '73','name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
            ['kode' => '7310','kode_provinsi' => '73','name' => 'KABUPATEN BARRU'],
            ['kode' => '7311','kode_provinsi' => '73','name' => 'KABUPATEN BONE'],
            ['kode' => '7312','kode_provinsi' => '73','name' => 'KABUPATEN SOPPENG'],
            ['kode' => '7313','kode_provinsi' => '73','name' => 'KABUPATEN WAJO'],
            ['kode' => '7314','kode_provinsi' => '73','name' => 'KABUPATEN SIDENRENG RAPPANG'],
            ['kode' => '7315','kode_provinsi' => '73','name' => 'KABUPATEN PINRANG'],
            ['kode' => '7316','kode_provinsi' => '73','name' => 'KABUPATEN ENREKANG'],
            ['kode' => '7317','kode_provinsi' => '73','name' => 'KABUPATEN LUWU'],
            ['kode' => '7318','kode_provinsi' => '73','name' => 'KABUPATEN TANA TORAJA'],
            ['kode' => '7322','kode_provinsi' => '73','name' => 'KABUPATEN LUWU UTARA'],
            ['kode' => '7325','kode_provinsi' => '73','name' => 'KABUPATEN LUWU TIMUR'],
            ['kode' => '7326','kode_provinsi' => '73','name' => 'KABUPATEN TORAJA UTARA'],
            ['kode' => '7371','kode_provinsi' => '73','name' => 'KOTA MAKASSAR'],
            ['kode' => '7372','kode_provinsi' => '73','name' => 'KOTA PAREPARE'],
            ['kode' => '7373','kode_provinsi' => '73','name' => 'KOTA PALOPO'],
            ['kode' => '7401','kode_provinsi' => '74','name' => 'KABUPATEN BUTON'],
            ['kode' => '7402','kode_provinsi' => '74','name' => 'KABUPATEN MUNA'],
            ['kode' => '7403','kode_provinsi' => '74','name' => 'KABUPATEN KONAWE'],
            ['kode' => '7404','kode_provinsi' => '74','name' => 'KABUPATEN KOLAKA'],
            ['kode' => '7405','kode_provinsi' => '74','name' => 'KABUPATEN KONAWE SELATAN'],
            ['kode' => '7406','kode_provinsi' => '74','name' => 'KABUPATEN BOMBANA'],
            ['kode' => '7407','kode_provinsi' => '74','name' => 'KABUPATEN WAKATOBI'],
            ['kode' => '7408','kode_provinsi' => '74','name' => 'KABUPATEN KOLAKA UTARA'],
            ['kode' => '7409','kode_provinsi' => '74','name' => 'KABUPATEN BUTON UTARA'],
            ['kode' => '7410','kode_provinsi' => '74','name' => 'KABUPATEN KONAWE UTARA'],
            ['kode' => '7411','kode_provinsi' => '74','name' => 'KABUPATEN KOLAKA TIMUR'],
            ['kode' => '7412','kode_provinsi' => '74','name' => 'KABUPATEN KONAWE KEPULAUAN'],
            ['kode' => '7413','kode_provinsi' => '74','name' => 'KABUPATEN MUNA BARAT'],
            ['kode' => '7414','kode_provinsi' => '74','name' => 'KABUPATEN BUTON TENGAH'],
            ['kode' => '7415','kode_provinsi' => '74','name' => 'KABUPATEN BUTON SELATAN'],
            ['kode' => '7471','kode_provinsi' => '74','name' => 'KOTA KENDARI'],
            ['kode' => '7472','kode_provinsi' => '74','name' => 'KOTA BAUBAU'],
            ['kode' => '7501','kode_provinsi' => '75','name' => 'KABUPATEN BOALEMO'],
            ['kode' => '7502','kode_provinsi' => '75','name' => 'KABUPATEN GORONTALO'],
            ['kode' => '7503','kode_provinsi' => '75','name' => 'KABUPATEN POHUWATO'],
            ['kode' => '7504','kode_provinsi' => '75','name' => 'KABUPATEN BONE BOLANGO'],
            ['kode' => '7505','kode_provinsi' => '75','name' => 'KABUPATEN GORONTALO UTARA'],
            ['kode' => '7571','kode_provinsi' => '75','name' => 'KOTA GORONTALO'],
            ['kode' => '7601','kode_provinsi' => '76','name' => 'KABUPATEN MAJENE'],
            ['kode' => '7602','kode_provinsi' => '76','name' => 'KABUPATEN POLEWALI MANDAR'],
            ['kode' => '7603','kode_provinsi' => '76','name' => 'KABUPATEN MAMASA'],
            ['kode' => '7604','kode_provinsi' => '76','name' => 'KABUPATEN MAMUJU'],
            ['kode' => '7605','kode_provinsi' => '76','name' => 'KABUPATEN MAMUJU UTARA'],
            ['kode' => '7606','kode_provinsi' => '76','name' => 'KABUPATEN MAMUJU TENGAH'],
            ['kode' => '8101','kode_provinsi' => '81','name' => 'KABUPATEN MALUKU TENGGARA BARAT'],
            ['kode' => '8102','kode_provinsi' => '81','name' => 'KABUPATEN MALUKU TENGGARA'],
            ['kode' => '8103','kode_provinsi' => '81','name' => 'KABUPATEN MALUKU TENGAH'],
            ['kode' => '8104','kode_provinsi' => '81','name' => 'KABUPATEN BURU'],
            ['kode' => '8105','kode_provinsi' => '81','name' => 'KABUPATEN KEPULAUAN ARU'],
            ['kode' => '8106','kode_provinsi' => '81','name' => 'KABUPATEN SERAM BAGIAN BARAT'],
            ['kode' => '8107','kode_provinsi' => '81','name' => 'KABUPATEN SERAM BAGIAN TIMUR'],
            ['kode' => '8108','kode_provinsi' => '81','name' => 'KABUPATEN MALUKU BARAT DAYA'],
            ['kode' => '8109','kode_provinsi' => '81','name' => 'KABUPATEN BURU SELATAN'],
            ['kode' => '8171','kode_provinsi' => '81','name' => 'KOTA AMBON'],
            ['kode' => '8172','kode_provinsi' => '81','name' => 'KOTA TUAL'],
            ['kode' => '8201','kode_provinsi' => '82','name' => 'KABUPATEN HALMAHERA BARAT'],
            ['kode' => '8202','kode_provinsi' => '82','name' => 'KABUPATEN HALMAHERA TENGAH'],
            ['kode' => '8203','kode_provinsi' => '82','name' => 'KABUPATEN KEPULAUAN SULA'],
            ['kode' => '8204','kode_provinsi' => '82','name' => 'KABUPATEN HALMAHERA SELATAN'],
            ['kode' => '8205','kode_provinsi' => '82','name' => 'KABUPATEN HALMAHERA UTARA'],
            ['kode' => '8206','kode_provinsi' => '82','name' => 'KABUPATEN HALMAHERA TIMUR'],
            ['kode' => '8207','kode_provinsi' => '82','name' => 'KABUPATEN PULAU MOROTAI'],
            ['kode' => '8208','kode_provinsi' => '82','name' => 'KABUPATEN PULAU TALIABU'],
            ['kode' => '8271','kode_provinsi' => '82','name' => 'KOTA TERNATE'],
            ['kode' => '8272','kode_provinsi' => '82','name' => 'KOTA TIDORE KEPULAUAN'],
            ['kode' => '9101','kode_provinsi' => '91','name' => 'KABUPATEN FAKFAK'],
            ['kode' => '9102','kode_provinsi' => '91','name' => 'KABUPATEN KAIMANA'],
            ['kode' => '9103','kode_provinsi' => '91','name' => 'KABUPATEN TELUK WONDAMA'],
            ['kode' => '9104','kode_provinsi' => '91','name' => 'KABUPATEN TELUK BINTUNI'],
            ['kode' => '9105','kode_provinsi' => '91','name' => 'KABUPATEN MANOKWARI'],
            ['kode' => '9106','kode_provinsi' => '91','name' => 'KABUPATEN SORONG SELATAN'],
            ['kode' => '9107','kode_provinsi' => '91','name' => 'KABUPATEN SORONG'],
            ['kode' => '9108','kode_provinsi' => '91','name' => 'KABUPATEN RAJA AMPAT'],
            ['kode' => '9109','kode_provinsi' => '91','name' => 'KABUPATEN TAMBRAUW'],
            ['kode' => '9110','kode_provinsi' => '91','name' => 'KABUPATEN MAYBRAT'],
            ['kode' => '9111','kode_provinsi' => '91','name' => 'KABUPATEN MANOKWARI SELATAN'],
            ['kode' => '9112','kode_provinsi' => '91','name' => 'KABUPATEN PEGUNUNGAN ARFAK'],
            ['kode' => '9171','kode_provinsi' => '91','name' => 'KOTA SORONG'],
            ['kode' => '9401','kode_provinsi' => '94','name' => 'KABUPATEN MERAUKE'],
            ['kode' => '9402','kode_provinsi' => '94','name' => 'KABUPATEN JAYAWIJAYA'],
            ['kode' => '9403','kode_provinsi' => '94','name' => 'KABUPATEN JAYAPURA'],
            ['kode' => '9404','kode_provinsi' => '94','name' => 'KABUPATEN NABIRE'],
            ['kode' => '9408','kode_provinsi' => '94','name' => 'KABUPATEN KEPULAUAN YAPEN'],
            ['kode' => '9409','kode_provinsi' => '94','name' => 'KABUPATEN BIAK NUMFOR'],
            ['kode' => '9410','kode_provinsi' => '94','name' => 'KABUPATEN PANIAI'],
            ['kode' => '9411','kode_provinsi' => '94','name' => 'KABUPATEN PUNCAK JAYA'],
            ['kode' => '9412','kode_provinsi' => '94','name' => 'KABUPATEN MIMIKA'],
            ['kode' => '9413','kode_provinsi' => '94','name' => 'KABUPATEN BOVEN DIGOEL'],
            ['kode' => '9414','kode_provinsi' => '94','name' => 'KABUPATEN MAPPI'],
            ['kode' => '9415','kode_provinsi' => '94','name' => 'KABUPATEN ASMAT'],
            ['kode' => '9416','kode_provinsi' => '94','name' => 'KABUPATEN YAHUKIMO'],
            ['kode' => '9417','kode_provinsi' => '94','name' => 'KABUPATEN PEGUNUNGAN BINTANG'],
            ['kode' => '9418','kode_provinsi' => '94','name' => 'KABUPATEN TOLIKARA'],
            ['kode' => '9419','kode_provinsi' => '94','name' => 'KABUPATEN SARMI'],
            ['kode' => '9420','kode_provinsi' => '94','name' => 'KABUPATEN KEEROM'],
            ['kode' => '9426','kode_provinsi' => '94','name' => 'KABUPATEN WAROPEN'],
            ['kode' => '9427','kode_provinsi' => '94','name' => 'KABUPATEN SUPIORI'],
            ['kode' => '9428','kode_provinsi' => '94','name' => 'KABUPATEN MAMBERAMO RAYA'],
            ['kode' => '9429','kode_provinsi' => '94','name' => 'KABUPATEN NDUGA'],
            ['kode' => '9430','kode_provinsi' => '94','name' => 'KABUPATEN LANNY JAYA'],
            ['kode' => '9431','kode_provinsi' => '94','name' => 'KABUPATEN MAMBERAMO TENGAH'],
            ['kode' => '9432','kode_provinsi' => '94','name' => 'KABUPATEN YALIMO'],
            ['kode' => '9433','kode_provinsi' => '94','name' => 'KABUPATEN PUNCAK'],
            ['kode' => '9434','kode_provinsi' => '94','name' => 'KABUPATEN DOGIYAI'],
            ['kode' => '9435','kode_provinsi' => '94','name' => 'KABUPATEN INTAN JAYA'],
            ['kode' => '9436','kode_provinsi' => '94','name' => 'KABUPATEN DEIYAI'],
            ['kode' => '9471','kode_provinsi' => '94','name' => 'KOTA JAYAPURA']
        ];

        DB::table('provinsis')->insert($provinsi);
        DB::table('kabupatens')->insert($kabupaten);
    }
}
